# Generated by Django 5.2.17 on 2026-09-25 00:54
#
# Django generated this file from applications/models.py. We normally let
# Django write migration files instead of creating them by hand.

# `migrations` contains database-change instructions. `models` contains the
# field classes needed to describe the table's columns.
from django.db import migrations, models


# A migration is a class describing one version change to the database schema.
class Migration(migrations.Migration):

    # This is the first migration for the applications app.
    initial = True

    # An empty list means no earlier applications migration must run first.
    dependencies = [
    ]

    # `operations` lists the structural changes this migration will make.
    operations = [
        # CreateModel tells Django to create a new database table for the
        # Internship model when we run `python manage.py migrate`.
        migrations.CreateModel(
            name='Internship',
            fields=[
                # Django added the primary-key id field automatically.
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                # These three fields came directly from our model class.
                ('name', models.CharField(max_length=200)),
                ('apply_by', models.DateField()),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('oa', 'Online assessment'), ('phone screen', 'Phone screen'), ('interview', 'Interview'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='applied', max_length=20)),
            ],
        ),
    ]
