# Generated by Django 5.2.17 on 2026-09-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('apply_by', models.DateField()),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('oa', 'Online assessment'), ('phone screen', 'Phone screen'), ('interview', 'Interview'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='applied', max_length=20)),
            ],
        ),
    ]
